### ISSUE TITLE
Kakao 로그인 이슈

### ISSUE THREAD

**Issue by ChocOZerO** [DrinKit-team-project/DrinKit-iOS#16]
카카오 동의 후 초기화면으로 돌아오는게 반복되는 이슈.
동의 후 로그인 된 홈 화면으로 들어갈 수 있도록 변경 필요.
테스트시 정상적으로 작동한 것으로 보아 특정 폰이나 환경에 영향을 받은 것으로 보임.

**Comment by somedd** [comment]
- 프로필 이미지를 못불러오는 사용자들이 있어서, 프로필 이미지를 받아오지 않고 SignUpView에서 편집하도록 변경하였습니다.
